schema_version: 1

context:
  version: 0.11.20260824

package:
  name: ibm-quantum-schemas
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/i/ibm-quantum-schemas/ibm_quantum_schemas-${{ version }}.tar.gz
  sha256: 8618358ba3c7d591141661bb71e075644f69d8a3b8af7fa4eb75ed50fcc59846

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >=${{ python_min }}
    - pybase64 >=1.4.0
    - pydantic >=2.11,<3.0.0
    - qiskit >=2.3.0,<3.0.0
    - samplomatic >=0.19.0
    - qiskit-qasm3-import >=0.6.0,<1.0.0
    - numpy >=1.26.2
tests:
  - python:
      imports:
        - ibm_quantum_schemas
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - '*'

about:
  summary: IBM Quantum Pydantic models.
  license: Apache-2.0
  license_file: LICENSE.txt
  homepage: https://github.com/Qiskit/ibm-quantum-schemas

extra:
  recipe-maintainers:
    - wshanks
